replicaCount: 1

image:
  repository: m0rgulnet/web
  pullPolicy: IfNotPresent

service:
 internalPort: 8001
 NodePort: 31116

answertext: v2.2

imagePullSecrets: []

serviceAccount:
    create: true
    name:

resources:
   limits:
     cpu: 300m
     memory: 150Mi
   requests:
     cpu: 200m
     memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
