replicaCount: 3

image:
  repository: m0rgulnet/web
  pullPolicy: IfNotPresent

service:
 internalPort: 8001
 NodePort: 32222

answertext: v2.3

imagePullSecrets: []

serviceAccount:
    create: true
    name:

resources:
   limits:
     cpu: 1000m
     memory: 500Mi
   requests:
     cpu: 500m
     memory: 250Mi

nodeSelector: {}

tolerations: []

affinity: {}
