apiVersion: v1
kind: Service
metadata:
  name: nginx-with-configmaps
  labels:
    app: nginx-with-configmaps
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: {{ .Values.service.NodePort }}
    port: {{ .Values.service.internalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: nginx-with-configmaps
