apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-with-configmaps
spec:
  hosts:
  - "*"
  gateways:
  - istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx-with-configmaps
        port:
          number: {{ .Values.service.internalPort }}
